<?php

namespace Database\Seeders;

use App\Models\Elemento;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ElementosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            ['id' => 1, 'elemento' => 'PUERTAS', 'area_id' => 1],
            ['id' => 2, 'elemento' => 'CORTINAS', 'area_id' => 1],
            ['id' => 3, 'elemento' => 'ILUMINACIÓN', 'area_id' => 1],
            ['id' => 4, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 1],
            ['id' => 5, 'elemento' => 'ESTACIÓN DE LAVADO DE MANOS', 'area_id' => 1],
            ['id' => 6, 'elemento' => 'COLGADORES', 'area_id' => 1],
            ['id' => 7, 'elemento' => 'PEDILUVIO', 'area_id' => 1],
            ['id' => 8, 'elemento' => 'PUERTAS', 'area_id' => 2],
            ['id' => 9, 'elemento' => 'CORTINAS', 'area_id' => 2],
            ['id' => 10, 'elemento' => 'ILUMINACIÓN', 'area_id' => 2],
            ['id' => 11, 'elemento' => 'MONITORES DE TEMPERATURA', 'area_id' => 2],
            ['id' => 12, 'elemento' => 'EVAPORADORES', 'area_id' => 2],
            ['id' => 13, 'elemento' => 'VALVULAS CLAMP', 'area_id' => 3],
            ['id' => 14, 'elemento' => 'ABRAZADERAS CLAMP', 'area_id' => 3],
            ['id' => 15, 'elemento' => 'ASPERSORES', 'area_id' => 3],
            ['id' => 16, 'elemento' => 'TUBERIA ACERO INOX', 'area_id' => 3],
            ['id' => 17, 'elemento' => 'RODILLOS', 'area_id' => 3],
            ['id' => 18, 'elemento' => 'FILTROS', 'area_id' => 3],
            ['id' => 19, 'elemento' => 'BANDEJA ACERO INOX', 'area_id' => 3],
            ['id' => 20, 'elemento' => 'PUERTAS', 'area_id' => 4],
            ['id' => 21, 'elemento' => 'CORTINAS DE AIRE', 'area_id' => 4],
            ['id' => 22, 'elemento' => 'ILUMINACIÓN', 'area_id' => 4],
            ['id' => 23, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 4],
            ['id' => 24, 'elemento' => 'URSCHEL MOD. 30', 'area_id' => 4],
            ['id' => 25, 'elemento' => 'URSCHEL MOD. 3C', 'area_id' => 4],
            ['id' => 26, 'elemento' => 'ESTRUCTURA DE LÍNEA DIRECTA', 'area_id' => 4],
            ['id' => 27, 'elemento' => 'MESAS DE RECORTE', 'area_id' => 4],
            ['id' => 28, 'elemento' => 'BÁSCULAS DE PLATAFORMA 1', 'area_id' => 4],
            ['id' => 29, 'elemento' => 'CORTADORA KRONEN (RECTIFICACIÓN DE CUCHILLAS)', 'area_id' => 4],
            ['id' => 30, 'elemento' => 'BANDA DE DESECHOS', 'area_id' => 4],
            ['id' => 31, 'elemento' => 'BÁSCULA DE PLATAFORMA 2', 'area_id' => 4],
            ['id' => 32, 'elemento' => 'TUBERIAS (AUSENCIA DE FUGAS)', 'area_id' => 4],
            ['id' => 33, 'elemento' => 'PUERTAS', 'area_id' => 5],
            ['id' => 34, 'elemento' => 'ILUMINACIÓN', 'area_id' => 5],
            ['id' => 35, 'elemento' => 'TUNEL 1', 'area_id' => 5],
            ['id' => 36, 'elemento' => 'MALLA 1', 'area_id' => 5],
            ['id' => 37, 'elemento' => 'TUNEL 2', 'area_id' => 5],
            ['id' => 38, 'elemento' => 'MALLA 2', 'area_id' => 5],
            ['id' => 39, 'elemento' => 'BANDA INTRALOX 1', 'area_id' => 5],
            ['id' => 40, 'elemento' => 'BANDA INTRALOX 2', 'area_id' => 5],
            ['id' => 41, 'elemento' => 'BLANCHER', 'area_id' => 5],
            ['id' => 42, 'elemento' => 'CHILLER', 'area_id' => 5],
            ['id' => 43, 'elemento' => 'URSCHEL MULTICORTES', 'area_id' => 5],
            ['id' => 44, 'elemento' => 'PUERTAS', 'area_id' => 6],
            ['id' => 45, 'elemento' => 'CORTINAS', 'area_id' => 6],
            ['id' => 46, 'elemento' => 'ILUMINACIÓN', 'area_id' => 6],
            ['id' => 47, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 6],
            ['id' => 48, 'elemento' => 'PEDILUVIO', 'area_id' => 6],
            ['id' => 49, 'elemento' => 'EVAPORADORES', 'area_id' => 6],
            ['id' => 50, 'elemento' => 'MONITORES DE TEMPERATURA', 'area_id' => 6],
            ['id' => 51, 'elemento' => 'TOLVAS DE LLENADO', 'area_id' => 6],
            ['id' => 52, 'elemento' => 'BANDAS TRANSPORTADORAS', 'area_id' => 6],
            ['id' => 53, 'elemento' => 'BASCULAS', 'area_id' => 6],
            ['id' => 54, 'elemento' => 'SELLADORAS', 'area_id' => 6],
            ['id' => 55, 'elemento' => 'SELLADORAS DE CAJAS', 'area_id' => 6],
            ['id' => 56, 'elemento' => 'DETECTOR DE METALES', 'area_id' => 6],
            ['id' => 57, 'elemento' => 'MESAS ACERO INOX', 'area_id' => 6],
            ['id' => 58, 'elemento' => 'PUERTAS', 'area_id' => 7],
            ['id' => 59, 'elemento' => 'CORTINAS', 'area_id' => 7],
            ['id' => 60, 'elemento' => 'ILUMINACIÓN', 'area_id' => 7],
            ['id' => 61, 'elemento' => 'RACKS', 'area_id' => 7],
            ['id' => 62, 'elemento' => 'EVAPORADORES', 'area_id' => 7],
            ['id' => 63, 'elemento' => 'MONITORES DE TEMPERATURA', 'area_id' => 7],
            ['id' => 64, 'elemento' => 'PUERTAS', 'area_id' => 8],
            ['id' => 65, 'elemento' => 'CORTINAS DE AIRE', 'area_id' => 8],
            ['id' => 66, 'elemento' => 'ILUMINACIÓN', 'area_id' => 8],
            ['id' => 67, 'elemento' => 'EVAPORADORES', 'area_id' => 8],
            ['id' => 68, 'elemento' => 'MONITOR DE TEMPERATURA', 'area_id' => 8],
            ['id' => 69, 'elemento' => 'BASCULA DE PLATAFORMA', 'area_id' => 8],
            ['id' => 70, 'elemento' => 'PUERTAS', 'area_id' => 9],
            ['id' => 71, 'elemento' => 'CORTINA', 'area_id' => 9],
            ['id' => 72, 'elemento' => 'ILUMINACIÓN', 'area_id' => 9],
            ['id' => 73, 'elemento' => 'LAVAMANOS', 'area_id' => 9],
            ['id' => 74, 'elemento' => 'CORTINAS DE AIRE', 'area_id' => 9],
            ['id' => 75, 'elemento' => 'PEDILUVIO', 'area_id' => 9],
            ['id' => 76, 'elemento' => 'COLGADORES DE BOTAS', 'area_id' => 9],
            ['id' => 77, 'elemento' => 'COLGADORES DE BATAS', 'area_id' => 9],
            ['id' => 78, 'elemento' => 'BANCA DIVISORA', 'area_id' => 9],
            ['id' => 79, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 9],
            ['id' => 80, 'elemento' => 'SELLOS DE PUERTAS', 'area_id' => 9],
            ['id' => 81, 'elemento' => 'LAVABOTAS', 'area_id' => 9],
            ['id' => 82, 'elemento' => 'BASES PARA CROCS / ZAPATOS', 'area_id' => 9],
            ['id' => 83, 'elemento' => 'PUERTAS + CORTINAS', 'area_id' => 10],
            ['id' => 84, 'elemento' => 'ILUMINACIÓN', 'area_id' => 10],
            ['id' => 85, 'elemento' => 'IMPRESORA MATERIAL EMPAQUE', 'area_id' => 10],
            ['id' => 86, 'elemento' => 'VENTANA DE TRANSICIÓN DE M.E.', 'area_id' => 10],
            ['id' => 172, 'elemento' => 'PUERTAS', 'area_id' => 11],
            ['id' => 173, 'elemento' => 'CORTINAS', 'area_id' => 11],
            ['id' => 174, 'elemento' => 'ILUMINACIÓN', 'area_id' => 11],
            ['id' => 175, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 11],
            ['id' => 176, 'elemento' => 'ESTACIÓN DE LAVADO DE MANOS', 'area_id' => 11],
            ['id' => 177, 'elemento' => 'COLGADORES', 'area_id' => 11],
            ['id' => 178, 'elemento' => 'PEDILUVIO', 'area_id' => 11],
            ['id' => 179, 'elemento' => 'PUERTAS', 'area_id' => 12],
            ['id' => 180, 'elemento' => 'CORTINAS', 'area_id' => 12],
            ['id' => 181, 'elemento' => 'ILUMINACIÓN', 'area_id' => 12],
            ['id' => 182, 'elemento' => 'MONITORES DE TEMPERATURA', 'area_id' => 12],
            ['id' => 183, 'elemento' => 'EVAPORADORES', 'area_id' => 12],
            ['id' => 184, 'elemento' => 'PUERTAS', 'area_id' => 13],
            ['id' => 185, 'elemento' => 'CORTINAS', 'area_id' => 13],
            ['id' => 186, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 13],
            ['id' => 187, 'elemento' => 'ILUMINACIÓN', 'area_id' => 13],
            ['id' => 188, 'elemento' => 'EVAPORADORES', 'area_id' => 13],
            ['id' => 189, 'elemento' => 'MONITORES DE TEMPERATURA', 'area_id' => 13],
            ['id' => 190, 'elemento' => 'MESAS DE RECORTE', 'area_id' => 13],
            ['id' => 191, 'elemento' => 'BÁSCULAS COSTOS', 'area_id' => 13],
            ['id' => 192, 'elemento' => 'CORTINAS', 'area_id' => 13],
            ['id' => 193, 'elemento' => 'ILUMINACIÓN', 'area_id' => 14],
            ['id' => 194, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 14],
            ['id' => 195, 'elemento' => 'ESTACIÓN DE LAVADO DE MANOS', 'area_id' => 14],
            ['id' => 196, 'elemento' => 'EVAPORADORES', 'area_id' => 14],
            ['id' => 197, 'elemento' => 'MONITORES DE TEMPERATURA', 'area_id' => 14],
            ['id' => 198, 'elemento' => 'CHILLER', 'area_id' => 14],
            ['id' => 199, 'elemento' => 'BANDA INSPECCIÓN', 'area_id' => 14],
            ['id' => 200, 'elemento' => 'LAVADORA 1', 'area_id' => 14],
            ['id' => 201, 'elemento' => 'FILTRO 1', 'area_id' => 14],
            ['id' => 202, 'elemento' => 'LAVADORA 2', 'area_id' => 14],
            ['id' => 203, 'elemento' => 'FILTRO 2', 'area_id' => 14],
            ['id' => 204, 'elemento' => 'LAVADORA 3', 'area_id' => 14],
            ['id' => 205, 'elemento' => 'FILTRO 3', 'area_id' => 14],
            ['id' => 206, 'elemento' => 'CUCHILLAS DE AIRE', 'area_id' => 14],
            ['id' => 207, 'elemento' => 'VIBRADOR', 'area_id' => 14],
            ['id' => 208, 'elemento' => 'CARRILERA CANASTA', 'area_id' => 14],
            ['id' => 209, 'elemento' => 'BASE GIRATORIA', 'area_id' => 14],
            ['id' => 210, 'elemento' => 'CENTRÍFUGAS', 'area_id' => 14],
            ['id' => 211, 'elemento' => 'TOLVA DE LLENADO DE CANASTA', 'area_id' => 14],
            ['id' => 212, 'elemento' => 'HIELADORA', 'area_id' => 14],
            ['id' => 213, 'elemento' => 'CORTINAS', 'area_id' => 14],
            ['id' => 214, 'elemento' => 'ILUMINACIÓN', 'area_id' => 15],
            ['id' => 215, 'elemento' => 'ESTACIÓN DE LAVADO DE MANOS', 'area_id' => 15],
            ['id' => 216, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 15],
            ['id' => 217, 'elemento' => 'PEDILUVIO', 'area_id' => 15],
            ['id' => 218, 'elemento' => 'EVAPORADORES', 'area_id' => 15],
            ['id' => 219, 'elemento' => 'MONITOR DE TEMPERATURA', 'area_id' => 15],
            ['id' => 220, 'elemento' => 'TOLVAS DE LLENADO', 'area_id' => 15],
            ['id' => 221, 'elemento' => 'BANDA TRANSPORTADORA', 'area_id' => 15],
            ['id' => 222, 'elemento' => 'BASCULAS', 'area_id' => 15],
            ['id' => 223, 'elemento' => 'SELLADORAS', 'area_id' => 15],
            ['id' => 224, 'elemento' => 'IMPRESORA DE EMPAQUE', 'area_id' => 15],
            ['id' => 225, 'elemento' => 'DETECTOR DE METALES', 'area_id' => 15],
            ['id' => 226, 'elemento' => 'MESA INOX', 'area_id' => 15],
            ['id' => 227, 'elemento' => 'CORTINAS', 'area_id' => 15],
            ['id' => 228, 'elemento' => 'PUERTAS', 'area_id' => 16],
            ['id' => 229, 'elemento' => 'ILUMINACIÓN', 'area_id' => 16],
            ['id' => 230, 'elemento' => 'EVAPORADORES', 'area_id' => 16],
            ['id' => 231, 'elemento' => 'MONITOR DE TEMPERATURA', 'area_id' => 16],
            ['id' => 232, 'elemento' => 'ESTRUCTURA', 'area_id' => 16],
            ['id' => 233, 'elemento' => 'CORTINAS', 'area_id' => 16],
            ['id' => 234, 'elemento' => 'PUERTAS', 'area_id' => 17],
            ['id' => 235, 'elemento' => 'ILUMINACIÓN', 'area_id' => 17],
            ['id' => 236, 'elemento' => 'EVPORADORES', 'area_id' => 17],
            ['id' => 237, 'elemento' => 'MONITOR DE TEMPERATURA', 'area_id' => 17],
            ['id' => 238, 'elemento' => 'CORTINAS', 'area_id' => 17],
            ['id' => 239, 'elemento' => 'ILUMINACIÓN', 'area_id' => 18],
            ['id' => 240, 'elemento' => 'PEDILUVIO', 'area_id' => 18],
            ['id' => 241, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 18],
            ['id' => 242, 'elemento' => 'ESTACIÓN DE LAVADO DE MANOS', 'area_id' => 18],
            ['id' => 243, 'elemento' => 'COLGADORES DE BOTAS', 'area_id' => 18],
            ['id' => 244, 'elemento' => 'COLGADORES DE BATAS', 'area_id' => 18],
            ['id' => 245, 'elemento' => 'BANCA DIVISORA', 'area_id' => 18],
            ['id' => 246, 'elemento' => 'ESTANTE DE ALMACENAMIENTO DE QUÍMICOS', 'area_id' => 18],
            ['id' => 247, 'elemento' => 'ARMARIO DE UTENSILIOS DE LIMPIEZA', 'area_id' => 18],
            ['id' => 248, 'elemento' => 'LOCKER DE INDUMENTARIA DE VISITA', 'area_id' => 18],
            ['id' => 249, 'elemento' => 'VENTANA DE TRANSICIÓN DE M.E.', 'area_id' => 18],
            ['id' => 250, 'elemento' => 'ESTACIÓN DE LAVADO DE OJOS', 'area_id' => 18],
            ['id' => 251, 'elemento' => 'SELLOS DE TODAS LAS PUERTAS', 'area_id' => 18],
        
            ['id' => 252, 'elemento' => 'PUERTAS', 'area_id' => 29],
            ['id' => 253, 'elemento' => 'CORTINAS', 'area_id' => 29],
            ['id' => 254, 'elemento' => 'ILUMINACIÓN', 'area_id' => 29],
            ['id' => 255, 'elemento' => 'DISPONIBILIDAD DE AGUA', 'area_id' => 29],
            ['id' => 256, 'elemento' => 'ESTACIÓN DE LAVADO DE MANOS', 'area_id' => 29],
            ['id' => 257, 'elemento' => 'COLGADORES', 'area_id' => 29],
            ['id' => 258, 'elemento' => 'PEDILUVIO', 'area_id' => 29],

            ['id' => 259, 'elemento' => 'PUERTAS', 'area_id' => 30],
            ['id' => 260, 'elemento' => 'CORTINAS', 'area_id' => 30],
            ['id' => 261, 'elemento' => 'ILUMINACIÓN', 'area_id' => 30],
            ['id' => 262, 'elemento' => 'EVAPORADORES', 'area_id' => 30],
            ['id' => 263, 'elemento' => 'BANDA TRANSPORTADORA #1', 'area_id' => 30],
            ['id' => 264, 'elemento' => 'BANDA RECOLECTORA #1', 'area_id' => 30],
            ['id' => 265, 'elemento' => 'BANDA HACIA PROCESO', 'area_id' => 30],
            ['id' => 266, 'elemento' => 'URSCCHEL MODELO G', 'area_id' => 30],



            ['id' => 267, 'elemento' => 'PUERTAS', 'area_id' => 31],
            ['id' => 268, 'elemento' => 'CORTINAS', 'area_id' => 31],
            ['id' => 269, 'elemento' => 'ILUMINACIÓN', 'area_id' => 31],
            ['id' => 270, 'elemento' => 'EVAPORADORES', 'area_id' => 31],
            ['id' => 271, 'elemento' => 'TUBERIA DRENAJE DEFROST', 'area_id' => 31],
            ['id' => 272, 'elemento' => 'CUBIERTAS', 'area_id' => 31],
            ['id' => 273, 'elemento' => 'SISTEMA DE PRENSA DE JUGO', 'area_id' => 31],
            ['id' => 274, 'elemento' => 'BOMBA DE AGUA', 'area_id' => 31],
            ['id' => 275, 'elemento' => 'BANDA ELEVADORA', 'area_id' => 31],
            ['id' => 276, 'elemento' => 'URSCHEL COMMITROL', 'area_id' => 31],
            ['id' => 277, 'elemento' => 'SEPARADOR DE JUGOS', 'area_id' => 31],
            ['id' => 278, 'elemento' => 'TANQUE RECIBIDOR', 'area_id' => 31],
            ['id' => 279, 'elemento' => 'BOMBA DE AGUA', 'area_id' => 31],
            ['id' => 280, 'elemento' => 'TANQUE #1', 'area_id' => 31],
            ['id' => 281, 'elemento' => 'TANQUE #2', 'area_id' => 31],
            ['id' => 282, 'elemento' => 'DEAREADOR CONTINUO', 'area_id' => 31],
            ['id' => 283, 'elemento' => 'HOMOGENIZADOR', 'area_id' => 31],
            ['id' => 284, 'elemento' => 'TANQUE #3', 'area_id' => 31],
            ['id' => 285, 'elemento' => 'TUBERÍAS DE AGUA', 'area_id' => 31],
            ['id' => 286, 'elemento' => 'TUBERÍA GRADO ALIMENTICIO', 'area_id' => 31],
            ['id' => 287, 'elemento' => 'CONTROLES ELÉCTRICO', 'area_id' => 31],
            ['id' => 288, 'elemento' => 'MUELLE DE CARGA RAMPA', 'area_id' => 31],


            ['id' => 289, 'elemento' => 'PUERTAS', 'area_id' => 32],
            ['id' => 290, 'elemento' => 'CORTINAS', 'area_id' => 32],
            ['id' => 291, 'elemento' => 'ILUMINACIÓN', 'area_id' => 32],
            ['id' => 292, 'elemento' => 'EVAPORADORES', 'area_id' => 32],
            ['id' => 293, 'elemento' => 'TUBERÍA DRENAJE DEFROST', 'area_id' => 32],
            ['id' => 294, 'elemento' => 'LLENADORA DE BOTELLAS', 'area_id' => 32],
            ['id' => 295, 'elemento' => 'TUBERIA DE AGUA', 'area_id' => 32],
            ['id' => 296, 'elemento' => 'TRANSPORTADOR DE BOTELLAS', 'area_id' => 32],
            ['id' => 297, 'elemento' => 'ESTRUCTURA', 'area_id' => 32],
            ['id' => 298, 'elemento' => 'MESA GIRATORIA', 'area_id' => 32],
            ['id' => 299, 'elemento' => 'CODIFICADORA', 'area_id' => 32],
            ['id' => 300, 'elemento' => 'TUBERIA ACERO INOXIDABLE', 'area_id' => 32],
            ['id' => 301, 'elemento' => 'RED NEUMATICA', 'area_id' => 32],
            ['id' => 302, 'elemento' => 'CONTROLES ELECTRICOS', 'area_id' => 32],


            ['id' => 303, 'elemento' => 'PUERTAS', 'area_id' => 33],
            ['id' => 304, 'elemento' => 'CORTINAS', 'area_id' => 33],
            ['id' => 305, 'elemento' => 'ILUMINACIÓN', 'area_id' => 33],
            ['id' => 306, 'elemento' => 'EQUIPO HIDRAULICO', 'area_id' => 33],
            ['id' => 307, 'elemento' => 'PROCESO ALTA PRESIÓN HPP', 'area_id' => 33],
            ['id' => 308, 'elemento' => 'TANQUE DE AGUA', 'area_id' => 33],
            ['id' => 309, 'elemento' => 'TUBERIAS DE AGUA', 'area_id' => 33],
            ['id' => 310, 'elemento' => 'RED NEUMATICA', 'area_id' => 33],



            ['id' => 311, 'elemento' => 'PUERTAS', 'area_id' => 34],
            ['id' => 312, 'elemento' => 'CORTINAS', 'area_id' => 34],
            ['id' => 313, 'elemento' => 'ILUMINACIÓN', 'area_id' => 34],
            ['id' => 314, 'elemento' => 'EVAPORADORES', 'area_id' => 34],
            ['id' => 315, 'elemento' => 'ESTRUCTURA', 'area_id' => 34],


            ['id' => 316, 'elemento' => 'PUERTAS', 'area_id' => 35],
            ['id' => 317, 'elemento' => 'CORTINAS', 'area_id' => 35],
            ['id' => 318, 'elemento' => 'ILUMINACIÓN', 'area_id' => 35],
            ['id' => 319, 'elemento' => 'EVAPORADORES', 'area_id' => 35],
            ['id' => 320, 'elemento' => 'MUELLE DE CARGA RAMPAS', 'area_id' => 35],
            ['id' => 321, 'elemento' => 'ESTACIÓN CARGA DE BATERÍAS', 'area_id' => 35],
            ['id' => 322, 'elemento' => 'BASCULA DE PLATAFORMA', 'area_id' => 35],
            ['id' => 323, 'elemento' => 'SELLOS DE ANDEN Y PUERTAS', 'area_id' => 35],


            ['id' => 324, 'elemento' => 'PUERTAS', 'area_id' => 36],
            ['id' => 325, 'elemento' => 'CORTINAS', 'area_id' => 36],
            ['id' => 326, 'elemento' => 'ILUMINACIÓN', 'area_id' => 36],
            ['id' => 327, 'elemento' => 'OFICINA MANTENIMIENTO', 'area_id' => 36],
            ['id' => 328, 'elemento' => 'UNIDAD BOMBA HIDRÁULICA 1', 'area_id' => 36],
            ['id' => 329, 'elemento' => 'UNIDAD BOMBA HIDRÁULICA 2', 'area_id' => 36],


            ['id' => 330, 'elemento' => 'PUERTAS', 'area_id' => 37],
            ['id' => 331, 'elemento' => 'CORTINAS', 'area_id' => 37],
            ['id' => 332, 'elemento' => 'ILUMINACIÓN', 'area_id' => 37],
            ['id' => 333, 'elemento' => 'EVAPORADORES', 'area_id' => 37],
            ['id' => 334, 'elemento' => 'BANDAS TRANSPORTADORAS', 'area_id' => 37],
            ['id' => 335, 'elemento' => 'SELLADORA DE CAJAS', 'area_id' => 37],
            ['id' => 336, 'elemento' => 'BASCULAS', 'area_id' => 37],
            ['id' => 337, 'elemento' => 'CONTROLES ELÉCTRICOS', 'area_id' => 37],
        
        ];

        Elemento::insert($data); 
    }
}
